---
title: "ETC2420 Group 53"
authors: "Sineth Wickramsinghe, Janiru Rathnapriya, Senuth Dias, Lawrence"
output: html_document
date: "2024-09-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, warning = FALSE, message = FALSE, error = FALSE)
library(tidyverse)
library(broom)
library(gridExtra)
library(MASS)

# Creates a histogram and smoothed histogram given a vector of values.
dataplot <- function(x, bins = 50, colour = "blue") {
  ggplot(tibble(x = x), aes(x = x, y = after_stat(density))) +
    geom_histogram(bins = bins, colour = colour, fill = colour, alpha = 0.2) +
    geom_density(colour = colour, fill = colour, alpha = 0.2) +
    theme_bw()
}
```

```{r Reading Bank Survey Data}
bank <- read_csv("banksurvey.csv")
```

# **Task #1**

### Descriptive Statistics on Customer Income

```{r Descriptive Statistics}

summary(bank$income) #Provides descriptive stats of customer income 
sd(bank$income) #Standard deviation of customer income 
```
### Visualising the Customer Income ($) Data 

```{r Visualising Data}
dataplot(bank$income) + 
  xlab("Customer Income ($)") + 
  ylab("Frequency") + 
  ggtitle("Distribution of Customer Income ($)") + 
  theme(plot.title = element_text(hjust = 0.5))
```


### Fitting Customer Income to Various Models

```{r Fitting Customer Income to Varuous Models}
normal_fit <- fitdistr(bank$income, "normal")
normal_fit %>% tidy()

gamma_fit <- fitdistr(bank$income, "gamma") 
gamma_fit %>% tidy()

exponential_fit <- fitdistr(bank$income, "exponential") 
exponential_fit %>% tidy()
```
### Normal Distribution QQ Plot Customer Income ($) 

```{r}
qqnorm(bank$income)
qqline(bank$income, col = "turquoise")
```

### Exponential Distribution QQ Plot Customer Income ($) 


```{r}
qqplot(qexp(ppoints(length(bank$income)), rate = exponential_fit$estimate), bank$income)
abline(0, 1, col = "turquoise")
```



### Gamma Distribution QQ Plot Customer Income ($) 


```{r}

```



## **Task 2**

*Central Limit Theorem Based Confidence Interval* 

## **Task 3**

## **Task 4**


## **Task 5**
